project:
  type: website
  output-dir: docs

website:
  title: "The Structure of Spanish"
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Syllabus"
        contents: 
        - Span_305_syllabus.qmd
        - calendar.qmd
      - section: "Semana 1"
        contents: 
        - semana1.qmd
        - semana1materials.qmd
      - section: "Semana 2"
        contents:
        - handout2.qmd
        - handout3.qmd
        - categorias.qmd
      - section: "Semana 4"
        contents: 
        - w4d1.qmd
        - w4d2.qmd
      - section: "Semana 6"
        contents: 
        - handout7.qmd
        - clausulas.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



